/*
 * Copyright 2019-2020 OpenFeign Contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package feign.assertions;

import feign.Header;
import feign.http.HttpHeader;
import feign.http.HttpRequest;
import java.util.Collection;
import org.assertj.core.api.AbstractObjectAssert;
import org.assertj.core.api.Assertions;
import org.assertj.core.internal.Iterables;
import org.assertj.core.util.Objects;

/**
 * Abstract base class for {@link HttpRequest} specific assertions - Generated by
 * CustomAssertionGenerator.
 */
@javax.annotation.Generated(value = "assertj-assertions-generator")
public abstract class AbstractHttpRequestAssert<S extends AbstractHttpRequestAssert<S, A>, A extends HttpRequest> extends
    AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractHttpRequestAssert}</code> to make assertions on actual
   * HttpRequest.
   *
   * @param actual the HttpRequest we want to make assertions on.
   */
  protected AbstractHttpRequestAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

  /**
   * Verifies that the actual HttpRequest's content contains the given byte elements.
   *
   * @param content the given elements that should be contained in actual HttpRequest's content.
   * @return this assertion object.
   * @throws AssertionError if the actual HttpRequest's content does not contain all given byte
   * elements.
   */
  public S hasContent(byte... content) {
    // check that actual HttpRequest we want to make assertions on is not null.
    isNotNull();

    // check that given byte varargs is not null.
    if (content == null) {
      failWithMessage("Expecting content parameter not to be null.");
    }

    // check with standard error message (use overridingErrorMessage before contains to set your own message).
    Assertions.assertThat(org.assertj.core.util.introspection.PropertySupport
        .propertyValueOf("content", actual, byte[].class)).contains(content);


    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual HttpRequest's content contains <b>only</b> the given byte elements and
   * nothing else in whatever order.
   *
   * @param content the given elements that should be contained in actual HttpRequest's content.
   * @return this assertion object.
   * @throws AssertionError if the actual HttpRequest's content does not contain all given byte
   * elements and nothing else.
   */
  public S hasOnlyContent(byte... content) {
    // check that actual HttpRequest we want to make assertions on is not null.
    isNotNull();

    // check that given byte varargs is not null.
    if (content == null) {
      failWithMessage("Expecting content parameter not to be null.");
    }

    // check with standard error message (use overridingErrorMessage before contains to set your own message).
    Assertions.assertThat(org.assertj.core.util.introspection.FieldSupport.EXTRACTION
        .fieldValue("content", byte[].class, actual)).containsOnly(content);

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual HttpRequest's content does not contain the given byte elements.
   *
   * @param content the given elements that should not be in actual HttpRequest's content.
   * @return this assertion object.
   * @throws AssertionError if the actual HttpRequest's content contains any given byte elements.
   */
  public S doesNotHaveContent(byte... content) {
    // check that actual HttpRequest we want to make assertions on is not null.
    isNotNull();

    // check that given byte varargs is not null.
    if (content == null) {
      failWithMessage("Expecting content parameter not to be null.");
    }

    // check with standard error message (use overridingErrorMessage before contains to set your own message).
    Assertions.assertThat(org.assertj.core.util.introspection.FieldSupport.EXTRACTION
        .fieldValue("content", byte[].class, actual)).doesNotContain(content);

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual HttpRequest has no content.
   *
   * @return this assertion object.
   * @throws AssertionError if the actual HttpRequest's content is not empty.
   */
  public S hasNoContent() {
    // check that actual HttpRequest we want to make assertions on is not null.
    isNotNull();

    // we override the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting :\n  <%s>\nnot to have content but had :\n  <%s>";

    // check that it is not empty
    if (org.assertj.core.util.introspection.FieldSupport.EXTRACTION
        .fieldValue("content", byte[].class, actual).length > 0) {
      failWithMessage(assertjErrorMessage, actual, java.util.Arrays.toString(
          org.assertj.core.util.introspection.FieldSupport.EXTRACTION
              .fieldValue("content", byte[].class, actual)));
    }

    // return the current assertion for method chaining
    return myself;
  }


  /**
   * Verifies that the actual HttpRequest's headers contains the given HttpHeader elements.
   *
   * @param headers the given elements that should be contained in actual HttpRequest's headers.
   * @return this assertion object.
   * @throws AssertionError if the actual HttpRequest's headers does not contain all given
   * HttpHeader elements.
   */
  public S hasHeaders(java.util.Collection<? extends Header> headers) {
    // check that actual HttpResponse we want to make assertions on is not null.
    isNotNull();

    // check that given HttpHeader collection is not null.
    if (headers == null) {
      failWithMessage("Expecting headers parameter not to be null.");
      return myself; // to fool Eclipse "Null pointer access" warning on toArray.
    }

    // check with standard error message, to set another message call: info.overridingErrorMessage("my error message");
    Iterables.instance().assertContains(info, org.assertj.core.util.introspection.PropertySupport.propertyValueOf("headers", actual, java.util.List.class), headers.toArray());

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual HttpRequest's headers contains <b>only</b> the given HttpHeader
   * elements and nothing else in whatever order.
   *
   * @param headers the given elements that should be contained in actual HttpRequest's headers.
   * @return this assertion object.
   * @throws AssertionError if the actual HttpRequest's headers does not contain all given
   * HttpHeader elements and nothing else.
   */
  public S hasOnlyHeaders(Collection<? extends HttpHeader> headers) {
    // check that actual HttpResponse we want to make assertions on is not null.
    isNotNull();

    // check that given HttpHeader collection is not null.
    if (headers == null) {
      failWithMessage("Expecting headers parameter not to be null.");
      return myself; // to fool Eclipse "Null pointer access" warning on toArray.
    }

    // check with standard error message, to set another message call: info.overridingErrorMessage("my error message");
    Iterables.instance().assertContainsOnly(info, org.assertj.core.util.introspection.FieldSupport.EXTRACTION.fieldValue("headers", java.util.List.class, actual), headers.toArray());

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual HttpRequest's headers does not contain the given HttpHeader elements.
   *
   * @param headers the given elements that should not be in actual HttpRequest's headers.
   * @return this assertion object.
   * @throws AssertionError if the actual HttpRequest's headers contains any given HttpHeader
   * elements.
   */
  public S doesNotHaveHeaders(HttpHeader... headers) {
    // check that actual HttpResponse we want to make assertions on is not null.
    isNotNull();

    // check that given HttpHeader varargs is not null.
    if (headers == null) failWithMessage("Expecting headers parameter not to be null.");

    // check with standard error message (use overridingErrorMessage before contains to set your own message).
    Iterables.instance().assertDoesNotContain(info, org.assertj.core.util.introspection.PropertySupport.propertyValueOf("headers", actual, java.util.List.class), headers);

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual HttpRequest has no headers.
   *
   * @return this assertion object.
   * @throws AssertionError if the actual HttpRequest's headers is not empty.
   */
  public S hasNoHeaders() {
    // check that actual HttpRequest we want to make assertions on is not null.
    isNotNull();

    // we override the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting :\n  <%s>\nnot to have headers but had :\n  <%s>";

    // check that it is not empty
    if (org.assertj.core.util.introspection.FieldSupport.EXTRACTION
        .fieldValue("headers", java.util.List.class, actual).iterator().hasNext()) {
      failWithMessage(assertjErrorMessage, actual,
          org.assertj.core.util.introspection.FieldSupport.EXTRACTION
              .fieldValue("headers", java.util.List.class, actual));
    }

    // return the current assertion for method chaining
    return myself;
  }


  /**
   * Verifies that the actual HttpRequest's method is equal to the given one.
   *
   * @param method the given method to compare the actual HttpRequest's method to.
   * @return this assertion object.
   * @throws AssertionError - if the actual HttpRequest's method is not equal to the given one.
   */
  public S hasMethod(feign.http.HttpMethod method) {
    // check that actual HttpRequest we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting method of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    feign.http.HttpMethod actualMethod = org.assertj.core.util.introspection.FieldSupport.EXTRACTION
        .fieldValue("method", feign.http.HttpMethod.class, actual);
    if (!Objects.areEqual(actualMethod, method)) {
      failWithMessage(assertjErrorMessage, actual, method, actualMethod);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual HttpRequest's options is equal to the given one.
   *
   * @param options the given options to compare the actual HttpRequest's options to.
   * @return this assertion object.
   * @throws AssertionError - if the actual HttpRequest's options is not equal to the given one.
   */
  public S hasOptions(feign.RequestOptions options) {
    // check that actual HttpRequest we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting options of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    feign.RequestOptions actualOptions = org.assertj.core.util.introspection.FieldSupport.EXTRACTION
        .fieldValue("options", feign.RequestOptions.class, actual);
    if (!Objects.areEqual(actualOptions, options)) {
      failWithMessage(assertjErrorMessage, actual, options, actualOptions);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual HttpRequest's uri is equal to the given one.
   *
   * @param uri the given uri to compare the actual HttpRequest's uri to.
   * @return this assertion object.
   * @throws AssertionError - if the actual HttpRequest's uri is not equal to the given one.
   */
  public S hasUri(java.net.URI uri) {
    // check that actual HttpRequest we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting uri of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    java.net.URI actualUri = org.assertj.core.util.introspection.FieldSupport.EXTRACTION
        .fieldValue("uri", java.net.URI.class, actual);
    if (!Objects.areEqual(actualUri, uri)) {
      failWithMessage(assertjErrorMessage, actual, uri, actualUri);
    }

    // return the current assertion for method chaining
    return myself;
  }

}
