# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#

# our job defaults
defaults: &defaults
  docker:
    - image: circleci/openjdk:11.0.2
  working_directory: ~/feignx
  environment:
    # Customize the JVM maximum heap limit
    MAVEN_OPTS: -Xmx3200m

version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - feignx-dependencies-{{ checksum "pom.xml" }}
            - feignx-dependencies-
      - run: mvn dependency:resolve-plugins go-offline:resolve-dependencies install -DskipTests=true
      - save_cache:
          paths:
            - ~/.m2
          key: feignx-dependencies-{{ checksum "pom.xml" }}
      - run: mvn -o test
      - store_test_results:
          path: core/target/surefire-reports
      - codecov/upload:
          file: tests/target/site/jacoco-aggregate/jacoco.xml
workflows:
  version: 2
  build:
    jobs:
      - build