package feign.assertions;

import feign.http.HttpResponse;
import org.assertj.core.api.AbstractObjectAssert;

/**
 * Abstract base class for {@link HttpResponse} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractHttpResponseAssert<S extends AbstractHttpResponseAssert<S, A>, A extends HttpResponse> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractHttpResponseAssert}</code> to make assertions on actual HttpResponse.
   * @param actual the HttpResponse we want to make assertions on.
   */
  protected AbstractHttpResponseAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

}
