package feign.assertions;

import feign.http.HttpRequest;
import org.assertj.core.api.AbstractObjectAssert;

/**
 * Abstract base class for {@link HttpRequest} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractHttpRequestAssert<S extends AbstractHttpRequestAssert<S, A>, A extends HttpRequest> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractHttpRequestAssert}</code> to make assertions on actual HttpRequest.
   * @param actual the HttpRequest we want to make assertions on.
   */
  protected AbstractHttpRequestAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

}
