package feign.assertions;

import feign.http.HttpHeader;
import org.assertj.core.api.AbstractObjectAssert;

/**
 * Abstract base class for {@link HttpHeader} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractHttpHeaderAssert<S extends AbstractHttpHeaderAssert<S, A>, A extends HttpHeader> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractHttpHeaderAssert}</code> to make assertions on actual HttpHeader.
   * @param actual the HttpHeader we want to make assertions on.
   */
  protected AbstractHttpHeaderAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

}
