package feign.assertions;

import feign.http.HttpHeader;

/**
 * {@link HttpHeader} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractHttpHeaderAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class HttpHeaderAssert extends AbstractHttpHeaderAssert<HttpHeaderAssert, HttpHeader> {

  /**
   * Creates a new <code>{@link HttpHeaderAssert}</code> to make assertions on actual HttpHeader.
   * @param actual the HttpHeader we want to make assertions on.
   */
  public HttpHeaderAssert(HttpHeader actual) {
    super(actual, HttpHeaderAssert.class);
  }

  /**
   * An entry point for HttpHeaderAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myHttpHeader)</code> and get specific assertion with code completion.
   * @param actual the HttpHeader we want to make assertions on.
   * @return a new <code>{@link HttpHeaderAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static HttpHeaderAssert assertThat(HttpHeader actual) {
    return new HttpHeaderAssert(actual);
  }
}
