package feign.assertions;

import feign.http.HttpResponse;

/**
 * {@link HttpResponse} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractHttpResponseAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class HttpResponseAssert extends AbstractHttpResponseAssert<HttpResponseAssert, HttpResponse> {

  /**
   * Creates a new <code>{@link HttpResponseAssert}</code> to make assertions on actual HttpResponse.
   * @param actual the HttpResponse we want to make assertions on.
   */
  public HttpResponseAssert(HttpResponse actual) {
    super(actual, HttpResponseAssert.class);
  }

  /**
   * An entry point for HttpResponseAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myHttpResponse)</code> and get specific assertion with code completion.
   * @param actual the HttpResponse we want to make assertions on.
   * @return a new <code>{@link HttpResponseAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static HttpResponseAssert assertThat(HttpResponse actual) {
    return new HttpResponseAssert(actual);
  }
}
